controller_list:
  - name: ""
    action_ns: position_trajectory_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    joints: ["joint_a1", "joint_a2", "joint_a3", "joint_a4", "joint_a5", "joint_a6"]
