# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 6.28318530718
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.0471975512
    min_position: -1.0471975512
  joint_a2:
    has_velocity_limits: true
    max_velocity: 5.23598775598
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.1745329252
    min_position: -1.5707963268
  joint_a3:
    has_velocity_limits: true
    max_velocity: 6.28318530718
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.3561944902
    min_position: 0
  joint_a4:
    has_velocity_limits: true
    max_velocity: 6.6497044501
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.5707963268
    min_position: -1.5707963268
  joint_a5:
    has_velocity_limits: true
    max_velocity: 6.77187749774
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.9198621772
    min_position: -1.5707963268
  joint_a6:
    has_velocity_limits: true
    max_velocity: 10.7337748998
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.8397243544
    min_position: -3.8397243544
